export const DEFAULT_QUESTIONS = [
  "What would he order at a restaurant?",
  "What's the first thing he'd talk about at a party?",
  "Pick one word to describe him.",
  "What movie would he make everyone watch?",
  "What's his go-to drink?",
  "If he had one free afternoon, how would he spend it?",
  "What dessert is he most likely to order?",
  "Name a topic he could lecture you on for an hour.",
  "What's something he does that surprises people?",
  "Which city suits him best — SF, Philly, New York, or Pune?",
  "What animal is he most like?",
  "What is the first topic he’d bring up at a dinner party to start a debate?",
  "Name a tech company he talks about the most (besides Meta).",
  "What’s the one piece of tech he owns that he’s most proud of?",
  "Name a famous tech founder he either loves or loves to roast.",
  "If he got punched (again), what did he likely say right before it happened?",
  "If he went to jail, what would the specific charge be?",
  "What’s the most likely reason he’d get kicked out of a high-end restaurant?",
  "If he became a cult leader, what would the cult be centered around?",
  "He’s at a bar and gets into a heated argument with a stranger. What is the argument about?"
];
